server {
    listen 80;

    location / {
        root /home/ibtisam/node-monolith-app/client/dist;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://localhost:5000/api/;
    }
}
